
/**
 * Auto-generated Runtime Configuration
 * Generated at: 2025-08-14T08:02:33.138Z
 * Environment: PRODUCTION
 * Version: 1.7.0
 * 
 * DO NOT EDIT - This file is automatically generated during build
 */

window.GLOBAL_CONFIG = {
  "environment": "PRODUCTION",
  "isProduction": true,
  "buildTime": "2025-08-14T08:02:33.138Z",
  "version": "1.7.0",
  "razorpay": {
    "environment": "PRODUCTION",
    "keyId": "rzp_live_BThHeYUshsR47c",
    "keySecret": "pUBaMpuNIukyXrPu33jrSeRQ",
    "webhookSecret": "1yK+,GI&U41("
  },
  "meta": {
    "pixelId": "726737740336667",
    "accessToken": "EAALBKYywVzQBPIJjQM7gzUxn2QbvxIIqGtCOBS8LmumDFznTnwmbNZAbW05v6OykhqyT35HqqKGed0hgK25ZAlpaW8p8VpsLWIpgKDfKvw5OZCHlwuDObs4ZCpq5wN1hBZCLdCugpAiHLOaoJjhc0U2bvAkZCpq6ZAghnwgJIE3b5oZAlpL1jd7WIq1g1f0dIgZDZD",
    "enabled": true
  },
  "analytics": {
    "gtmId": null,
    "ga4MeasurementId": null,
    "ga4PropertyId": null,
    "enabled": false
  },
  "zapier": {
    "webhookUrl": "https://hooks.zapier.com/hooks/catch/23606322/u34shwt/",
    "leadWebhookUrl": "https://hooks.zapier.com/hooks/catch/23606322/u6t1nd5/",
    "enabled": true
  },
  "performance": {
    "webhookTimeout": 15000,
    "retryAttempts": 3,
    "enableCaching": false,
    "enableCompression": true
  },
  "security": {
    "enableCSP": true,
    "trustedDomains": [
      "lotuslion.in",
      "www.lotuslion.in",
      "checkout.razorpay.com",
      "api.razorpay.com",
      "connect.facebook.net",
      "www.facebook.com",
    ],
    "allowedScriptSources": [
      "'self'",
      "'unsafe-inline'",
      "https://checkout.razorpay.com",
      "https://connect.facebook.net",
    ]
  }
};

// Backward compatibility
window.GLOBAL_RAZORPAY_ENVIRONMENT = "PRODUCTION";
window.GLOBAL_RAZORPAY_KEY_ID = "rzp_live_BThHeYUshsR47c";

// Configuration helpers
window.getConfig = function(path) {
    return path.split('.').reduce((obj, key) => obj && obj[key], window.GLOBAL_CONFIG);
};

window.isProduction = function() {
    return window.GLOBAL_CONFIG.isProduction;
};

window.isSandbox = function() {
    return !window.GLOBAL_CONFIG.isProduction;
};

console.log('✅ Runtime configuration loaded:', {
    environment: window.GLOBAL_CONFIG.environment,
    version: window.GLOBAL_CONFIG.version,
    razorpay: !!window.GLOBAL_CONFIG.razorpay.keyId,
    meta: window.GLOBAL_CONFIG.meta.enabled,
    analytics: false,
    zapier: window.GLOBAL_CONFIG.zapier.enabled
});
