
/**
 * Auto-generated Runtime Configuration
 * Generated at: 2025-08-13T22:01:03.834Z
 * Environment: SANDBOX
 * Version: 1.7.0
 * 
 * DO NOT EDIT - This file is automatically generated during build
 */

window.GLOBAL_CONFIG = {
  "environment": "SANDBOX",
  "isProduction": false,
  "buildTime": "2025-08-13T22:01:03.834Z",
  "version": "1.7.0",
  "razorpay": {
    "environment": "SANDBOX"
  },
  "meta": {
    "pixelId": "726737740336667",
    "enabled": false
  },
  "analytics": {
    "gtmId": "GTM-M3JWN37C",
    "ga4MeasurementId": "G-XXXXXXXXXX",
    "ga4PropertyId": "491307873",
    "enabled": false
  },
  "zapier": {
    "enabled": false
  },
  "performance": {
    "webhookTimeout": 15000,
    "retryAttempts": 3,
    "enableCaching": false,
    "enableCompression": true
  },
  "security": {
    "enableCSP": true,
    "trustedDomains": [
      "lotuslion.in",
      "www.lotuslion.in",
      "checkout.razorpay.com",
      "api.razorpay.com",
      "connect.facebook.net",
      "www.facebook.com",
      "www.googletagmanager.com",
      "www.google-analytics.com"
    ],
    "allowedScriptSources": [
      "'self'",
      "'unsafe-inline'",
      "https://checkout.razorpay.com",
      "https://connect.facebook.net",
      "https://www.googletagmanager.com"
    ]
  }
};

// Backward compatibility
window.GLOBAL_RAZORPAY_ENVIRONMENT = "SANDBOX";
window.GLOBAL_RAZORPAY_KEY_ID = "";

// Configuration helpers
window.getConfig = function(path) {
    return path.split('.').reduce((obj, key) => obj && obj[key], window.GLOBAL_CONFIG);
};

window.isProduction = function() {
    return window.GLOBAL_CONFIG.isProduction;
};

window.isSandbox = function() {
    return !window.GLOBAL_CONFIG.isProduction;
};

console.log('✅ Runtime configuration loaded:', {
    environment: window.GLOBAL_CONFIG.environment,
    version: window.GLOBAL_CONFIG.version,
    razorpay: !!window.GLOBAL_CONFIG.razorpay.keyId,
    meta: window.GLOBAL_CONFIG.meta.enabled,
    analytics: window.GLOBAL_CONFIG.analytics.enabled,
    zapier: window.GLOBAL_CONFIG.zapier.enabled
});
