#!/bin/bash

echo "Deploying to Vercel..."
echo ""
echo "To deploy this project to Vercel, please run:"
echo ""
echo "1. vercel login  (if not already logged in)"
echo "2. vercel --prod"
echo ""
echo "Or if you have a Vercel token:"
echo "vercel --prod --token YOUR_TOKEN"
echo ""
echo "The project is ready for deployment with all requested changes:"
echo "✅ Hero section simplified with clickable CTA"
echo "✅ Logo removed from hero"
echo "✅ Pricing updated to ₹1,999 (was ₹9,999)"
echo "✅ Course renamed to 'The Complete Indian Investor'"
echo "✅ Video course references removed"
echo "✅ Card layouts fixed (2x2 and 3-per-row)"
echo "✅ Learning journey accordion removed"
echo "✅ Rohit's introduction simplified"
echo "✅ Mobile responsive design improved"